databases:
  - name: bookaction-db
    plan: free
    region: oregon
    databaseName: bookaction

services:
  - type: web
    name: bookaction-backend
    env: node
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: npm run build && npx prisma migrate deploy
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: bookaction-db
          property: connectionString
